# Cosine Similarity Assignment

## Using Cosine Distance

#### Find the senator whose voting record is closest to Rhode Island senator, Lincoln Chafee.

In [5]:
# Import pandas and numpy
import pandas as pd
import numpy as np

In [6]:
# Read the .csv file for senate votes
df1 = pd.read_csv("senate_votes.csv")
# Used head() function to preview the first five rows of the data; can remove head() function to view full list
df1.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
0      Akaka     D    HI  -1  -1   1   1   1  -1  -1  ...    1   -1   -1    1   
1  Alexander     R    TN   1   1   1   1   1   1   1  ...    1    1    1    1   
2     Allard     R    CO   1   1   1   1   1   1   1  ...    1    1    1    1   
3      Allen     R    VA   1   1   1   1   1   1   1  ...    1    1    1    1   
4     Baucus     D    MT  -1   1   1   1   1   1  -1  ...    1   -1    1    0   

   B41  B42  B43  B44  B45  B46  
0   -1    1   -1    1    1   -1  
1    1    1    1    0    1    1  
2    1    1    1    1    1    1  
3    1    1    1    1    1    1  
4    1    1   -1    1    1    1  

[5 rows x 49 columns]

In [7]:
# Isolate rows to show only Rhode Island (RI) Senators
rhode_island_senators = df1[df1['State'] == 'RI']
rhode_island_senators

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
18  Chafee     R    RI   1  -1   1   1   1   1  -1  ...    1   -1   -1    1   
76    Reed     D    RI   1  -1   1   1   1  -1  -1  ...    1   -1   -1    1   

    B41  B42  B43  B44  B45  B46  
18    1    1   -1    1    1   -1  
76    1    1   -1    1    1   -1  

[2 rows x 49 columns]

Given the information above, we can conclude that row 18 must be Lincoln Chafee because there are only two senators in Rhode Island and we know that Lincoln Chafee is a Rhode Island senator.

In [9]:
# Isolate the row that contains Chafee's name in it
l_Chafee = rhode_island_senators[rhode_island_senators['Name'] == 'Chafee']
l_Chafee

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
18  Chafee     R    RI   1  -1   1   1   1   1  -1  ...    1   -1   -1    1   

    B41  B42  B43  B44  B45  B46  
18    1    1   -1    1    1   -1  

[1 rows x 49 columns]

In [10]:
# Exclude the first few columns so we can contain only the numeric values in an array
lincoln_Chafee = l_Chafee.iloc[:, 3:]
lincoln_Chafee

B1  B2  B3  B4  B5  B6  B7  B8  B9  B10  ...  B37  B38  B39  B40  B41  \
18   1  -1   1   1   1   1  -1   1   1    1  ...    1   -1   -1    1    1   

    B42  B43  B44  B45  B46  
18    1   -1    1    1   -1  

[1 rows x 46 columns]

In [11]:
# Turn the data information into an array
lincoln_C_array = np.array(lincoln_Chafee)
print(lincoln_C_array)

[[ 1 -1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  0  1  1  1  1  1
   1  1 -1  1  1  1  1  0  1  1  0  1  1 -1 -1  1  1  1 -1  1  1 -1]]


In [12]:
# Create an array for a list of senators
senator_list = np.array(df1.iloc[:, 3:])
print(senator_list)

[[-1 -1  1 ...  1  1 -1]
 [ 1  1  1 ...  0  1  1]
 [ 1  1  1 ...  1  1  1]
 ...
 [ 1 -1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [-1 -1  1 ...  1  1 -1]]


In [13]:
# Create cosine distance function
def cosine_distance(u, v):
    dot_product = np.dot(u,v)
    u_magnitude = np.linalg.norm(u)
    v_magnitude = np.linalg.norm(v)
    return (1 - (dot_product) / (u_magnitude * v_magnitude))

In [14]:
# Find the cosine distance between Chafee and the other senators and contain the cosine distances in an array
distance_list = []

for i in range(len(senator_list)):
        row_i = senator_list[i]
        cosDistance = cosine_distance(lincoln_C_array[0], senator_list[i])
        distance_list.append(cosDistance)
# Add a new column to contain a list of cosine distances
df1['distances'] = distance_list

# Find the 5 cosine distances from ascending order
top_5_senators = df1.sort_values('distances', ascending = True)
# Used iloc[] to ignore the first sorted row since it would display Chafee's row information
top_5_senators.iloc[1:, :].head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B38  B39  B40  B41  \
52  Jeffords     I    VT   1  -1   1  -1   1   1  -1  ...   -1   -1    1    0   
71    Murray     D    WA  -1  -1   1   1   1  -1  -1  ...   -1   -1    1    1   
8   Bingaman     D    NM   1   0   1   1   1   1  -1  ...   -1   -1    1   -1   
63   Lincoln     D    AR   1   1   1   1   1   1  -1  ...   -1    1    1    1   
16  Cantwell     D    WA   1   1   1   1   1  -1  -1  ...   -1   -1    1    1   

    B42  B43  B44  B45  B46  distances  
52    1   -1    1    1   -1   0.090674  
71    1   -1    1    1   -1   0.158874  
8     1   -1    1    1   -1   0.181607  
63    1   -1    1    1    1   0.213036  
16    1   -1    1    1    1   0.213036  

[5 rows x 50 columns]

From the table above, Jeffords's voting record is the closest to Lincoln Chafee because Jeffords has the closest cosine distance to zero.

#### Find the senator who disagrees most with Pennsylvania senator, Rick Santorum.

In [17]:
# Read the .csv file again (this is to get a new table without the distances column)
df2 = pd.read_csv("senate_votes.csv")
df2.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
0      Akaka     D    HI  -1  -1   1   1   1  -1  -1  ...    1   -1   -1    1   
1  Alexander     R    TN   1   1   1   1   1   1   1  ...    1    1    1    1   
2     Allard     R    CO   1   1   1   1   1   1   1  ...    1    1    1    1   
3      Allen     R    VA   1   1   1   1   1   1   1  ...    1    1    1    1   
4     Baucus     D    MT  -1   1   1   1   1   1  -1  ...    1   -1    1    0   

   B41  B42  B43  B44  B45  B46  
0   -1    1   -1    1    1   -1  
1    1    1    1    0    1    1  
2    1    1    1    1    1    1  
3    1    1    1    1    1    1  
4    1    1   -1    1    1    1  

[5 rows x 49 columns]

In [18]:
# Isolate rows to show only Pennsylvania (PA) Senators
penn_senators = df2[df2['State'] == 'PA']
penn_senators

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
81  Santorum     R    PA   0   1   1   1   1   1   1  ...    1    1    1    1   
88   Specter     R    PA   1   1   1   1   1   1   1  ...    1    1    1    1   

    B41  B42  B43  B44  B45  B46  
81    1    1    1    1    1    1  
88    1    1    1    1    1    1  

[2 rows x 49 columns]

Given the information above, we can conclude that row 81 must be Rick Santorum because there are only two senators in Pennsylvania and we know that Rick Santorum is a Pennsylvania senator.

In [20]:
# Isolate the row that contains Santorum's name in it
r_santorum = penn_senators[penn_senators['Name'] == 'Santorum']
r_santorum

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
81  Santorum     R    PA   0   1   1   1   1   1   1  ...    1    1    1    1   

    B41  B42  B43  B44  B45  B46  
81    1    1    1    1    1    1  

[1 rows x 49 columns]

In [21]:
# Exclude the first few columns so we can contain only the numeric values in an array
rick_santorum = r_santorum.iloc[:, 3:]
rick_santorum

B1  B2  B3  B4  B5  B6  B7  B8  B9  B10  ...  B37  B38  B39  B40  B41  \
81   0   1   1   1   1   1   1   1   1    1  ...    1    1    1    1    1   

    B42  B43  B44  B45  B46  
81    1    1    1    1    1  

[1 rows x 46 columns]

In [22]:
# Turn the data information into an array
rick_s_array = np.array(rick_santorum)
print(rick_s_array)

[[ 0  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1 -1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]]


In [23]:
# Create an array for a list of senators
senator_list2 = np.array(df2.iloc[:, 3:])
print(senator_list2)

[[-1 -1  1 ...  1  1 -1]
 [ 1  1  1 ...  0  1  1]
 [ 1  1  1 ...  1  1  1]
 ...
 [ 1 -1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [-1 -1  1 ...  1  1 -1]]


In [24]:
# Find the cosine distance between Santorum and the other senators and contain the cosine distances in an array
distance_list2 = []

for j in range(len(senator_list2)):
        row_j = senator_list2[j]
        cosDistance = cosine_distance(rick_s_array[0], senator_list2[j])
        distance_list2.append(cosDistance)
# Add a new column to contain a list of cosine distances
df2['distances'] = distance_list2

# Find the five cosine distances from descending order
bottom_5_senators = df2.sort_values('distances', ascending = False)
bottom_5_senators.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B38  B39  B40  B41  \
39  Feingold     D    WI  -1  -1   1  -1   1  -1  -1  ...   -1   -1    1   -1   
76      Reed     D    RI   1  -1   1   1   1  -1  -1  ...   -1   -1    1    1   
0      Akaka     D    HI  -1  -1   1   1   1  -1  -1  ...   -1   -1    1   -1   
60     Leahy     D    VT  -1  -1   1   1   1  -1  -1  ...   -1   -1    1   -1   
10     Boxer     D    CA  -1  -1   1   1   1  -1  -1  ...   -1    1    1   -1   

    B42  B43  B44  B45  B46  distances  
39    1   -1    1    1   -1   0.934062  
76    1   -1    1    1   -1   0.714268  
0     1   -1    1    1   -1   0.707847  
60    1   -1    1    1   -1   0.707847  
10    1   -1    1    1   -1   0.688889  

[5 rows x 50 columns]

From the table above, Feingold's voting record disagrees most with Rick Santorum because Feingold has the farthest cosine distance from zero.

#### Vermont senator Jim Jeffords was an Independent. Choose 5 Democratic and 5 Republican (or more) senators. Compare Jefford's record with each of these 10 senators. 
##### Would you classify Jeffords as closer to the Democrats or a Republicans?

In [27]:
# Read the .csv file again
df3 = pd.read_csv("senate_votes.csv")
df3.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
0      Akaka     D    HI  -1  -1   1   1   1  -1  -1  ...    1   -1   -1    1   
1  Alexander     R    TN   1   1   1   1   1   1   1  ...    1    1    1    1   
2     Allard     R    CO   1   1   1   1   1   1   1  ...    1    1    1    1   
3      Allen     R    VA   1   1   1   1   1   1   1  ...    1    1    1    1   
4     Baucus     D    MT  -1   1   1   1   1   1  -1  ...    1   -1    1    0   

   B41  B42  B43  B44  B45  B46  
0   -1    1   -1    1    1   -1  
1    1    1    1    0    1    1  
2    1    1    1    1    1    1  
3    1    1    1    1    1    1  
4    1    1   -1    1    1    1  

[5 rows x 49 columns]

In [28]:
# Separate the data by party (Democratic or Republican)

# Isolate rows by Democrat Party
demo = df3[df3['Party'] == 'D']
demo.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
0     Akaka     D    HI  -1  -1   1   1   1  -1  -1  ...    1   -1   -1    1   
4    Baucus     D    MT  -1   1   1   1   1   1  -1  ...    1   -1    1    0   
5      Bayh     D    IN   1  -1   1   1   1   1  -1  ...    1   -1    1   -1   
7     Biden     D    DE  -1  -1   1   1   1   1  -1  ...    1   -1    1    1   
8  Bingaman     D    NM   1   0   1   1   1   1  -1  ...    1   -1   -1    1   

   B41  B42  B43  B44  B45  B46  
0   -1    1   -1    1    1   -1  
4    1    1   -1    1    1    1  
5    1    1   -1    1    1   -1  
7    1    1   -1    1    1   -1  
8   -1    1   -1    1    1   -1  

[5 rows x 49 columns]

In [29]:
# Isolate rows by Republican Party
rep = df3[df3['Party'] == 'R']
rep.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
1  Alexander     R    TN   1   1   1   1   1   1   1  ...    1    1    1    1   
2     Allard     R    CO   1   1   1   1   1   1   1  ...    1    1    1    1   
3      Allen     R    VA   1   1   1   1   1   1   1  ...    1    1    1    1   
6    Bennett     R    UT   1   1   1   1   1   1   1  ...    1    1    1    1   
9       Bond     R    MO   1   1   1   1   1   1   1  ...    1    1    1    1   

   B41  B42  B43  B44  B45  B46  
1    1    1    1    0    1    1  
2    1    1    1    1    1    1  
3    1    1    1    1    1    1  
6    1    1    1    1    1    1  
9    1    1    1    1    1    1  

[5 rows x 49 columns]

In [30]:
# Selecting 5 random rows for each party using random_state, which is effectively the same thing as specifying a random seed
# Choose 5 random Democrats and set the seed to 42
random_demo = demo.sample(5, random_state = 42)
random_demo

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  \
79  Rockefeller     D    WV   1   1   1   1   1  -1  -1  ...    1    1    1   
59   Lautenberg     D    NJ  -1  -1   1   1   1  -1  -1  ...    1    1   -1   
60        Leahy     D    VT  -1  -1   1   1   1  -1  -1  ...    0   -1   -1   
77         Reid     D    NV  -1  -1   1   1   1   1  -1  ...    1   -1   -1   
75        Pryor     D    AR  -1   1   1   1   1   1  -1  ...    1    1    1   

    B40  B41  B42  B43  B44  B45  B46  
79    1    1    0   -1    1    1   -1  
59    1    1    1   -1    1    1   -1  
60    1   -1    1   -1    1    1   -1  
77    1    1    1   -1    1    1   -1  
75    1    1    1   -1    1    1    1  

[5 rows x 49 columns]

In [31]:
# Choose 5 random Republicans and set the seed to 42
random_rep = rep.sample(5, random_state = 42)
random_rep

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  \
49     Inhofe     R    OK   1   1   1   1   1   1   1  ...    1    1    1   
11  Brownback     R    KS   1   1   1   1   1   1   1  ...    1    1    1   
51    Isakson     R    GA   1   1   1   1   1   1   1  ...    1    1    1   
23    Coleman     R    MN   1   1   1   1   1   1  -1  ...    1    1    1   
31     DeWine     R    OH   1   1   1   1   1   1  -1  ...    1    1    1   

    B40  B41  B42  B43  B44  B45  B46  
49    1    0   -1    1    1    1    1  
11    1    1    1    1    1    1    1  
51    1    1    1    1    1    1    1  
23    1    1    1   -1    1    1    1  
31    1    1    1   -1    1    1    1  

[5 rows x 49 columns]

In [32]:
# List out the senators of Vermont to identify where Jim Jeffords is
vermont_senators = df3[df3['State'] == 'VT']
vermont_senators

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
52  Jeffords     I    VT   1  -1   1  -1   1   1  -1  ...    1   -1   -1    1   
60     Leahy     D    VT  -1  -1   1   1   1  -1  -1  ...    0   -1   -1    1   

    B41  B42  B43  B44  B45  B46  
52    0    1   -1    1    1   -1  
60   -1    1   -1    1    1   -1  

[2 rows x 49 columns]

Given the information above, we can conclude that row 52 must be Jim Jeffords because there are only two senators in Vermont and we know that Jim Jeffords is a Vermont senator.

In [34]:
# Isolate the row to show only Jim Jeffords
j_jeffords = vermont_senators[vermont_senators['Name'] == 'Jeffords']
j_jeffords

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
52  Jeffords     I    VT   1  -1   1  -1   1   1  -1  ...    1   -1   -1    1   

    B41  B42  B43  B44  B45  B46  
52    0    1   -1    1    1   -1  

[1 rows x 49 columns]

In [35]:
# Exclude the first few columns so we can contain only the numeric values in an array
jim_jeff = j_jeffords.iloc[:, 3:]
jim_jeff

B1  B2  B3  B4  B5  B6  B7  B8  B9  B10  ...  B37  B38  B39  B40  B41  \
52   1  -1   1  -1   1   1  -1   1   1    1  ...    1   -1   -1    1    0   

    B42  B43  B44  B45  B46  
52    1   -1    1    1   -1  

[1 rows x 46 columns]

In [36]:
# Turn the data information for into an array
jeff_array = np.array(jim_jeff)
print(jeff_array)

[[ 1 -1  1 -1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1 -1  1  1  1  1  1  1  1  1  1  1 -1 -1  1  0  1 -1  1  1 -1]]


In [37]:
# Create an array for the random list of Democrats
demo_array = np.array(random_demo.iloc[:, 3:])
print(demo_array)

[[ 1  1  1  1  1 -1 -1  0  1  0  1  0  1  1 -1  1  0  1 -1  0  1  1  1  1
  -1  1 -1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  0 -1  1  1 -1]
 [-1 -1  1  1  1 -1 -1  1  1  1  1  1 -1  1 -1  1  1  1 -1  1  1  1  1  1
  -1  1 -1 -1  1  1  1  1  1  1  1 -1  1  1 -1  1  1  1 -1  1  1 -1]
 [-1 -1  1  1  1 -1 -1  1  1  1  1  1  1  1 -1  1  1  1  0  1  1  1  1  1
  -1  1 -1 -1  1  1  1  1  1  1  1 -1  0 -1 -1  1 -1  1 -1  1  1 -1]
 [-1 -1  1  1  1  1 -1  1  1  1  1  1  1  1 -1  1  1  1 -1  1  1  1  1  1
  -1  1  1  1  1  1  1  1  1  1  1 -1  1 -1 -1  1  1  1 -1  1  1 -1]
 [-1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1]]


In [38]:
# Create an array for the random list of Republicans
rep_array = np.array(random_rep.iloc[:, 3:])
print(rep_array)

[[ 1  1  1  1  1  1  1 -1  1 -1  1 -1  1  1  1  1  1  1  1 -1  1  1  1 -1
   1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  0 -1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1 -1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1  1 -1  1  1  1  1  1  1  1  1  1  1  1 -1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1
   1  1  1  1  1  1  1  1  1  1  1  0  1  1  1  1  1  1 -1  1  1  1]
 [ 1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1]]


In [39]:
# Find the cosine distance between Jefford and the Democrats
demo_list = []

for i in range(len(demo_array)):
        row_i = demo_array[i]
        cosDistance = cosine_distance(jeff_array[0], demo_array[i])
        demo_list.append(cosDistance)
# Add a new column to contain a list of cosine distances
random_demo['distances'] = demo_list

# Find the five cosine distances from descending order
demo_senator_cos = random_demo.sort_values('distances', ascending = True)
demo_senator_cos.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B38  B39  B40  \
77         Reid     D    NV  -1  -1   1   1   1   1  -1  ...   -1   -1    1   
75        Pryor     D    AR  -1   1   1   1   1   1  -1  ...    1    1    1   
60        Leahy     D    VT  -1  -1   1   1   1  -1  -1  ...   -1   -1    1   
59   Lautenberg     D    NJ  -1  -1   1   1   1  -1  -1  ...    1   -1    1   
79  Rockefeller     D    WV   1   1   1   1   1  -1  -1  ...    1    1    1   

    B41  B42  B43  B44  B45  B46  distances  
77    1    1   -1    1    1   -1   0.318640  
75    1    1   -1    1    1    1   0.318640  
60   -1    1   -1    1    1   -1   0.348273  
59    1    1   -1    1    1   -1   0.450516  
79    1    0   -1    1    1   -1   0.505025  

[5 rows x 50 columns]

In [40]:
# Find the cosine distance between Jefford and the Republicans
rep_list = []

for i in range(len(rep_array)):
        row_i = rep_array[i]
        cosDistance = cosine_distance(jeff_array[0], rep_array[i])
        rep_list.append(cosDistance)
# Add a new column to contain a list of cosine distances
random_rep['distances'] = rep_list

# Find the five cosine distances from ascending order
rep_senator_cos = random_rep.sort_values('distances', ascending = True)
rep_senator_cos.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B38  B39  B40  \
31     DeWine     R    OH   1   1   1   1   1   1  -1  ...    1    1    1   
23    Coleman     R    MN   1   1   1   1   1   1  -1  ...    1    1    1   
11  Brownback     R    KS   1   1   1   1   1   1   1  ...    1    1    1   
51    Isakson     R    GA   1   1   1   1   1   1   1  ...    1    1    1   
49     Inhofe     R    OK   1   1   1   1   1   1   1  ...    1    1    1   

    B41  B42  B43  B44  B45  B46  distances  
31    1    1   -1    1    1    1   0.318640  
23    1    1   -1    1    1    1   0.333333  
11    1    1    1    1    1    1   0.450516  
51    1    1    1    1    1    1   0.494475  
49    0   -1    1    1    1    1   0.666667  

[5 rows x 50 columns]

In [41]:
# Find the average cosine distance for Democrats
demo_distance_avg = 0

for i in range(len(demo_list)):
    demo_distance_avg += demo_list[i]
demo_distance_avg /= len(demo_list)

print('Cosine Distance Average for Democrats:', demo_distance_avg)   

Cosine Distance Average for Democrats: 0.38821906932143346


In [42]:
# Find the average cosine distance for Republicans
rep_distance_avg = 0

for i in range(len(rep_list)):
    rep_distance_avg += rep_list[i]
rep_distance_avg /= len(rep_list)

print('Cosine Distance Average for Republicans:', rep_distance_avg) 

Cosine Distance Average for Republicans: 0.45272628401155224


Comparing Jefford's records with each of these 10 senators, I would classify Jeffords as closer to the Democrats because the average cosine distance for Democrats is closer to zero than the average cosine distance for Republicans.

### Extra Credit: Testing out a similar formatted file of voting records of 100 US senators in between 2023-2024

In [45]:
# Reading the csv file we created for senator votes in between 2023-2024
senate_2023 = pd.read_csv("senator_votes_2023-2024.csv")
senate_2023

Name Party State  B1  B2  B3  B4  B5  B6  B7  B8  B9  B10
0      Baldwin     D    WI   1  -1   1   1   1   1   1  -1  -1    1
1     Barrasso     R    WY  -1   1   1   0  -1   0  -1   1   1    0
2       Bennet     D    CO   1  -1  -1   1   1   1   1  -1   1    1
3    Blackburn     R    TN   1   1  -1  -1  -1  -1   1   1  -1    1
4   Blumenthal     D    CT   1  -1   1   1   1   1   1  -1   1    1
..         ...   ...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...
95       Welch     D    VT   1  -1   1   1  -1   1   1  -1  -1    1
96  Whitehouse     D    RI   1  -1   1   1   1   1   1  -1   1    1
97      Wicker     R    MS   1   1   1   1   1   1  -1   1   1    1
98       Wyden     D    OR   1  -1   1   1   1   1   1  -1  -1    1
99       Young     R    IN   1   1   1   1   1   1  -1   1   1    1

[100 rows x 13 columns]